export const PHOTOS_STORAGE_KEY = 'BERSERKERCUT_PHOTOS_V1';
export const CLOUD_CONSENT_STORAGE_KEY = 'BERSERKERCUT_CLOUD_CONSENT_V1';
export const MEAL_PHOTOS_STORAGE_KEY = 'BERSERKERCUT_MEAL_PHOTOS_V1';
export const PRIVACY_CONSENT_SHOWN = 'BERSERKERCUT_PRIVACY_CONSENT_SHOWN_V1';
